<?php

/**
 * Copyright © Alexandru-Manuel Carabus All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var Template $block
 * @var ViewModelRegistry $viewModels
 * @var HeroiconsOutline $heroicons
 * @var Escaper $escaper
 */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$allowedHtmlTags = ['a', 'span', 'b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];

// phpcs:disable Generic.Files.LineLength
?>

<div x-data="{
    notifications: [],
    fetchNotifications() {
        fetch('<?= $escaper->escapeHtml($block->getUrl('hawksama/check/notifications')) ?>', {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
            }
        })
        .then(response => response.json())
        .then(data => {
            this.notifications = data.notifications || [];
        });
    }
}"
     x-init="fetchNotifications()"
     @cart-item-removed.window="fetchNotifications()"
     @cart-item-added.window="fetchNotifications()">
    <template x-for="notification in notifications" :key="notification">
        <div class="alert flex items-center p-4 my-4 text-yellow-800 border-t-4 border-yellow-300 bg-yellow-50 dark:text-yellow-300 dark:bg-gray-800 dark:border-yellow-800"
             role="alert">
            <div>
                <?= $heroicons->informationCircleHtml('', 28, 28, ['aria-hidden' => 'true']) ?>
            </div>
            <div class="ms-3">
                <span x-html="notification.message"></span>
            </div>
        </div>
    </template>
</div>
