<?php

/**
 * Copyright © Alexandru-Manuel Carabus All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var Template $block
 * @var ViewModelRegistry $viewModels
 * @var HeroiconsOutline $heroicons
 * @var Escaper $escaper
 */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$allowedHtmlTags = ['a', 'span', 'b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];

// Predefine the icons for each type
$icons = [
    0 => $heroicons->exclamationCircleHtml('', 28, 28, ['aria-hidden' => 'true']), // Error
    1 => $heroicons->informationCircleHtml('', 28, 28, ['aria-hidden' => 'true']), // Warning
    2 => $heroicons->informationCircleHtml('', 28, 28, ['aria-hidden' => 'true']), // Information
    3 => $heroicons->checkCircleHtml('', 28, 28, ['aria-hidden' => 'true']), // Success
];
?>

<div x-data="{
    notifications: [],
    fetchNotifications() {
        fetch('<?= $escaper->escapeHtml($block->getUrl('hawksama/check/notifications')) ?>', {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
            }
        })
        .then(response => response.json())
        .then(data => {
            this.notifications = data.notifications || [];
        });
    },
    getNotificationStyles(type) {
        const styles = {
            0: {
                class: 'bg-red-50 border-red-500 text-red-800'
            },
            1: {
                class: 'bg-yellow-50 border-yellow-500 text-yellow-800'
            },
            2: {
                class: 'bg-blue-50 border-blue-500 text-blue-800'
            },
            3: {
                class: 'bg-green-50 border-green-500 text-green-800'
            },
        };
        return styles[type] || styles[0]; // Default to Error if type is unknown
    }
}"
     x-init="fetchNotifications()"
     @cart-item-removed.window="fetchNotifications()"
     @cart-item-added.window="fetchNotifications()">
    <template x-for="notification in notifications" :key="notification.id">
        <div class="alert flex items-center p-4 my-4 border-t-4"
             :class="`${getNotificationStyles(notification.type).class}`"
             role="alert">
            <div>
                <template x-if="notification.type === 0"><?= /* @noEscape */  $icons[0] ?></template>
                <template x-if="notification.type === 1"><?= /* @noEscape */  $icons[1] ?></template>
                <template x-if="notification.type === 2"><?= /* @noEscape */  $icons[2] ?></template>
                <template x-if="notification.type === 3"><?= /* @noEscape */  $icons[3] ?></template>
            </div>
            <div class="ms-3">
                <span x-html="notification.message"></span>
            </div>
        </div>
    </template>
</div>
