<?php

/**
 * Copyright © Alexandru-Manuel Carabus All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Hawksama\HyvaProductRuleNotifier\ViewModel\NotificationViewModel;

/**
 * @var Template $block
 * @var ViewModelRegistry $viewModels
 * @var NotificationViewModel $viewModel
 * @var HeroiconsOutline $heroicons
 * @var Escaper $escaper
 */

$viewModel = $viewModels->require(NotificationViewModel::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
$allowedHtmlTags = ['a','span','b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];
$notifications = $viewModel->getNotifications();
?>
<?php if (!empty($notifications)): ?>
    <div class="notifications mt-8 space-y-4">
        <?php foreach ($notifications as $notification): ?>
            <?php
            $type = $notification->getNotificationType();
            $styles = [
                0 => [
                    'class' => 'bg-red-50 border-red-500 text-red-800',
                    'icon' => $heroicons->exclamationCircleHtml('', 28, 28, ['aria-hidden' => 'true']),
                ],
                1 => [
                    'class' => 'bg-yellow-50 border-yellow-500 text-yellow-800',
                    'icon' => $heroicons->informationCircleHtml('', 28, 28, ['aria-hidden' => 'true']),
                ],
                2 => [
                    'class' => 'bg-blue-50 border-blue-500 text-blue-800',
                    'icon' => $heroicons->informationCircleHtml('', 28, 28, ['aria-hidden' => 'true']),
                ],
                3 => [
                    'class' => 'bg-green-50 border-green-500 text-green-800',
                    'icon' => $heroicons->checkCircleHtml('', 28, 28, ['aria-hidden' => 'true']),
                ],
            ];
            $style = $styles[$type] ?? $styles[0]; // Default to Error style if type is unknown
            ?>
            <div class="notification">
                <div id="alert-<?= $escaper->escapeHtmlAttr($type) ?>"
                     class="flex items-center p-4 border-t-4 <?= $escaper->escapeHtmlAttr($style['class']) ?>"
                     role="alert">
                    <div>
                        <?= /* @noEscape */  $style['icon'] ?>
                    </div>
                    <div class="ms-3">
                        <?= $escaper->escapeHtml($notification->getDescription(), $allowedHtmlTags); ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
